import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const EN_DIR = join(process.cwd(), "locales", "en");
const OUT_FILE = join(process.cwd(), "src", "lib", "i18n", "keys.gen.ts");

function flattenKeys(obj: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && !Array.isArray(v)) {
      keys.push(...flattenKeys(v as Record<string, unknown>, path));
    } else {
      keys.push(path);
    }
  }
  return keys;
}

export function generateKeysFile(): void {
  const files = readdirSync(EN_DIR).filter((f) => f.endsWith(".json"));
  const blocks = files.map((file) => {
    const namespace = file.replace(/\.json$/, "");
    const content = JSON.parse(readFileSync(join(EN_DIR, file), "utf-8"));
    const keys = flattenKeys(content);
    const union = keys.length > 0 ? keys.map((k) => `"${k}"`).join(" | ") : "never";
    return `  ${namespace}: ${union};`;
  });

  const out = `// AUTO-GENERATED by src/lib/i18n/generate-keys.ts — do not edit by hand.
export type NamespaceKeyMap = {
${blocks.join("\n")}
};
`;
  writeFileSync(OUT_FILE, out);
}
