// AUTO-GENERATED by src/lib/i18n/generate-keys.ts — do not edit by hand.
export type NamespaceKeyMap = {
  auth: "sign_in_title" | "sign_up_title" | "sign_in_sub" | "sign_up_sub" | "full_name" | "phone" | "phone_invalid" | "email" | "password" | "remember" | "forgot" | "sign_in" | "sign_up" | "or" | "google" | "apple" | "apple_soon" | "new_here" | "have_account" | "switch_sign_up" | "switch_sign_in" | "business" | "join_team" | "check_email" | "signed_in" | "welcome" | "reset_sent" | "enter_email" | "role_legend" | "role_client" | "role_client_hint" | "role_business" | "role_business_hint" | "password_strength.weak" | "password_strength.good" | "password_strength.strong" | "password_rule.length" | "password_rule.letter" | "password_rule.number" | "password_rule.upper" | "password_rule.lower" | "password_rule.symbol";
  booking: "cancel_confirm_body" | "customer.cancel_title" | "customer.keep" | "customer.confirm" | "admin.cancel_title" | "admin.keep" | "admin.confirm";
  business: never;
  common: "brand" | "tagline" | "sign_in" | "footer" | "language" | "nav.home" | "nav.search" | "nav.bookings" | "nav.favorites" | "nav.profile" | "menu.customers" | "menu.business" | "menu.explore" | "menu.search" | "menu.bookings" | "menu.favorites" | "menu.account" | "menu.notifications" | "menu.dashboard" | "menu.list_business" | "menu.business_sign_in" | "menu.staff_sign_in" | "menu.business_dashboard" | "menu.create_account" | "menu.sign_out";
  customer: never;
  errors: never;
  marketplace: "hero_title" | "hero_sub" | "search_placeholder" | "search_btn" | "suggestions" | "stats" | "categories_title" | "nearby_title" | "nearby_sub" | "see_all" | "open" | "closed" | "instant" | "km" | "book" | "steps_title" | "steps" | "cta_title" | "cta_sub" | "cta_btn" | "categories.hair" | "categories.barber" | "categories.nails" | "categories.spa" | "categories.makeup" | "categories.lashes" | "business_type_fallback" | "details" | "driving_minutes" | "walking_minutes" | "hero_badge" | "search_clear" | "filter_country" | "filter_all_countries" | "filter_state" | "filter_city" | "filter_shop_type" | "filter_all_shop_types" | "shops_match" | "home_search_placeholder" | "filter_by_location_type" | "filter_all_states" | "filter_all_cities" | "filter_pick_country_first" | "back_home" | "dallty_home" | "search_shop_name_placeholder" | "search_clear_aria" | "filters_aria" | "sort_top_rated" | "sort_nearest" | "sort_most_reviewed" | "searching" | "shops_found" | "clear_all" | "nearby_salons_btn" | "near_me_btn" | "location_blocked" | "calculating_travel_times" | "no_shops_match" | "try_different_filters" | "clear_all_filters" | "sorted_by" | "sort_by_distance" | "sort_by_reviews" | "sort_by_rating";
  notifications: "title" | "mark_all_read" | "loading" | "empty" | "unread";
  payments: never;
  platform: never;
  reports: never;
  reviews: never;
  services: never;
  settings: never;
  staff: never;
  validation: never;
};
