// AUTO-GENERATED by src/lib/i18n/generate-keys.ts — do not edit by hand.
export type NamespaceKeyMap = {
  auth: never;
  booking: never;
  business: never;
  common: never;
  customer: never;
  errors: never;
  marketplace: never;
  notifications: never;
  payments: never;
  platform: never;
  reports: never;
  reviews: never;
  services: never;
  settings: never;
  staff: never;
  validation: never;
};
