/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthEmailHookRouteImport } from './routes/auth/email-hook'
import { Route as BusinessIdBusinessIdRouteImport } from './routes/business-id.$businessId'
import { Route as BusinessBusinessSlugRouteImport } from './routes/business.$businessSlug'
import { Route as BusinessSignupRouteImport } from './routes/business/signup'
import { Route as SalonSalonIdRouteImport } from './routes/salon.$salonId'
import { Route as StaffSignupRouteImport } from './routes/staff/signup'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminAvailabilityRouteImport } from './routes/_authenticated/admin/availability'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedAdminConfirmationsRouteImport } from './routes/_authenticated/admin/confirmations'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin/marketplace'
import { Route as AuthenticatedAdminMyAppointmentsRouteImport } from './routes/_authenticated/admin/my-appointments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedRescheduleBookingIdRouteImport } from './routes/_authenticated/reschedule.$bookingId'
import { Route as AuthenticatedAdminPlatformAuthPoliciesRouteImport } from './routes/_authenticated/admin/platform/auth-policies'
import { Route as AuthenticatedAdminPlatformBusinessesRouteImport } from './routes/_authenticated/admin/platform/businesses'
import { Route as AuthenticatedAdminPlatformCategoriesRouteImport } from './routes/_authenticated/admin/platform/categories'
import { Route as AuthenticatedAdminPlatformCountriesRouteImport } from './routes/_authenticated/admin/platform/countries'
import { Route as AuthenticatedAdminPlatformDirectoryRouteImport } from './routes/_authenticated/admin/platform/directory'
import { Route as AuthenticatedAdminPlatformEmailDomainsRouteImport } from './routes/_authenticated/admin/platform/email-domains'
import { Route as AuthenticatedAdminPlatformMarketplaceRouteImport } from './routes/_authenticated/admin/platform/marketplace'
import { Route as AuthenticatedAdminPlatformOverviewRouteImport } from './routes/_authenticated/admin/platform/overview'
import { Route as AuthenticatedAdminPlatformReservedSlugsRouteImport } from './routes/_authenticated/admin/platform/reserved-slugs'
import { Route as AuthenticatedAdminPlatformUsersRouteImport } from './routes/_authenticated/admin/platform/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthEmailHookRoute = AuthEmailHookRouteImport.update({
  id: '/email-hook',
  path: '/email-hook',
  getParentRoute: () => AuthRoute,
} as any)
const BusinessIdBusinessIdRoute = BusinessIdBusinessIdRouteImport.update({
  id: '/business-id/$businessId',
  path: '/business-id/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessSlugRoute = BusinessBusinessSlugRouteImport.update({
  id: '/business/$businessSlug',
  path: '/business/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSignupRoute = BusinessSignupRouteImport.update({
  id: '/business/signup',
  path: '/business/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonSalonIdRoute = SalonSalonIdRouteImport.update({
  id: '/salon/$salonId',
  path: '/salon/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignupRoute = StaffSignupRouteImport.update({
  id: '/staff/signup',
  path: '/staff/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvailabilityRoute =
  AuthenticatedAdminAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfirmationsRoute =
  AuthenticatedAdminConfirmationsRouteImport.update({
    id: '/confirmations',
    path: '/confirmations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarketplaceRoute =
  AuthenticatedAdminMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMyAppointmentsRoute =
  AuthenticatedAdminMyAppointmentsRouteImport.update({
    id: '/my-appointments',
    path: '/my-appointments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedRescheduleBookingIdRoute =
  AuthenticatedRescheduleBookingIdRouteImport.update({
    id: '/reschedule/$bookingId',
    path: '/reschedule/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlatformAuthPoliciesRoute =
  AuthenticatedAdminPlatformAuthPoliciesRouteImport.update({
    id: '/platform/auth-policies',
    path: '/platform/auth-policies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformBusinessesRoute =
  AuthenticatedAdminPlatformBusinessesRouteImport.update({
    id: '/platform/businesses',
    path: '/platform/businesses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformCategoriesRoute =
  AuthenticatedAdminPlatformCategoriesRouteImport.update({
    id: '/platform/categories',
    path: '/platform/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformCountriesRoute =
  AuthenticatedAdminPlatformCountriesRouteImport.update({
    id: '/platform/countries',
    path: '/platform/countries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformDirectoryRoute =
  AuthenticatedAdminPlatformDirectoryRouteImport.update({
    id: '/platform/directory',
    path: '/platform/directory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformEmailDomainsRoute =
  AuthenticatedAdminPlatformEmailDomainsRouteImport.update({
    id: '/platform/email-domains',
    path: '/platform/email-domains',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformMarketplaceRoute =
  AuthenticatedAdminPlatformMarketplaceRouteImport.update({
    id: '/platform/marketplace',
    path: '/platform/marketplace',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformOverviewRoute =
  AuthenticatedAdminPlatformOverviewRouteImport.update({
    id: '/platform/overview',
    path: '/platform/overview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformReservedSlugsRoute =
  AuthenticatedAdminPlatformReservedSlugsRouteImport.update({
    id: '/platform/reserved-slugs',
    path: '/platform/reserved-slugs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformUsersRoute =
  AuthenticatedAdminPlatformUsersRouteImport.update({
    id: '/platform/users',
    path: '/platform/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/email-hook': typeof AuthEmailHookRoute
  '/business-id/$businessId': typeof BusinessIdBusinessIdRoute
  '/business/$businessSlug': typeof BusinessBusinessSlugRoute
  '/business/signup': typeof BusinessSignupRoute
  '/salon/$salonId': typeof SalonSalonIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/confirmations': typeof AuthenticatedAdminConfirmationsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/my-appointments': typeof AuthenticatedAdminMyAppointmentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/reschedule/$bookingId': typeof AuthenticatedRescheduleBookingIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/platform/auth-policies': typeof AuthenticatedAdminPlatformAuthPoliciesRoute
  '/admin/platform/businesses': typeof AuthenticatedAdminPlatformBusinessesRoute
  '/admin/platform/categories': typeof AuthenticatedAdminPlatformCategoriesRoute
  '/admin/platform/countries': typeof AuthenticatedAdminPlatformCountriesRoute
  '/admin/platform/directory': typeof AuthenticatedAdminPlatformDirectoryRoute
  '/admin/platform/email-domains': typeof AuthenticatedAdminPlatformEmailDomainsRoute
  '/admin/platform/marketplace': typeof AuthenticatedAdminPlatformMarketplaceRoute
  '/admin/platform/overview': typeof AuthenticatedAdminPlatformOverviewRoute
  '/admin/platform/reserved-slugs': typeof AuthenticatedAdminPlatformReservedSlugsRoute
  '/admin/platform/users': typeof AuthenticatedAdminPlatformUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/email-hook': typeof AuthEmailHookRoute
  '/business-id/$businessId': typeof BusinessIdBusinessIdRoute
  '/business/$businessSlug': typeof BusinessBusinessSlugRoute
  '/business/signup': typeof BusinessSignupRoute
  '/salon/$salonId': typeof SalonSalonIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/confirmations': typeof AuthenticatedAdminConfirmationsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/my-appointments': typeof AuthenticatedAdminMyAppointmentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/reschedule/$bookingId': typeof AuthenticatedRescheduleBookingIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/platform/auth-policies': typeof AuthenticatedAdminPlatformAuthPoliciesRoute
  '/admin/platform/businesses': typeof AuthenticatedAdminPlatformBusinessesRoute
  '/admin/platform/categories': typeof AuthenticatedAdminPlatformCategoriesRoute
  '/admin/platform/countries': typeof AuthenticatedAdminPlatformCountriesRoute
  '/admin/platform/directory': typeof AuthenticatedAdminPlatformDirectoryRoute
  '/admin/platform/email-domains': typeof AuthenticatedAdminPlatformEmailDomainsRoute
  '/admin/platform/marketplace': typeof AuthenticatedAdminPlatformMarketplaceRoute
  '/admin/platform/overview': typeof AuthenticatedAdminPlatformOverviewRoute
  '/admin/platform/reserved-slugs': typeof AuthenticatedAdminPlatformReservedSlugsRoute
  '/admin/platform/users': typeof AuthenticatedAdminPlatformUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/email-hook': typeof AuthEmailHookRoute
  '/business-id/$businessId': typeof BusinessIdBusinessIdRoute
  '/business/$businessSlug': typeof BusinessBusinessSlugRoute
  '/business/signup': typeof BusinessSignupRoute
  '/salon/$salonId': typeof SalonSalonIdRoute
  '/staff/signup': typeof StaffSignupRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/confirmations': typeof AuthenticatedAdminConfirmationsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin/my-appointments': typeof AuthenticatedAdminMyAppointmentsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/reschedule/$bookingId': typeof AuthenticatedRescheduleBookingIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/platform/auth-policies': typeof AuthenticatedAdminPlatformAuthPoliciesRoute
  '/_authenticated/admin/platform/businesses': typeof AuthenticatedAdminPlatformBusinessesRoute
  '/_authenticated/admin/platform/categories': typeof AuthenticatedAdminPlatformCategoriesRoute
  '/_authenticated/admin/platform/countries': typeof AuthenticatedAdminPlatformCountriesRoute
  '/_authenticated/admin/platform/directory': typeof AuthenticatedAdminPlatformDirectoryRoute
  '/_authenticated/admin/platform/email-domains': typeof AuthenticatedAdminPlatformEmailDomainsRoute
  '/_authenticated/admin/platform/marketplace': typeof AuthenticatedAdminPlatformMarketplaceRoute
  '/_authenticated/admin/platform/overview': typeof AuthenticatedAdminPlatformOverviewRoute
  '/_authenticated/admin/platform/reserved-slugs': typeof AuthenticatedAdminPlatformReservedSlugsRoute
  '/_authenticated/admin/platform/users': typeof AuthenticatedAdminPlatformUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/verify-otp'
    | '/admin'
    | '/account'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/auth/email-hook'
    | '/business-id/$businessId'
    | '/business/$businessSlug'
    | '/business/signup'
    | '/salon/$salonId'
    | '/staff/signup'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/calendar'
    | '/admin/confirmations'
    | '/admin/customers'
    | '/admin/marketplace'
    | '/admin/my-appointments'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/reschedule/$bookingId'
    | '/admin/'
    | '/admin/platform/auth-policies'
    | '/admin/platform/businesses'
    | '/admin/platform/categories'
    | '/admin/platform/countries'
    | '/admin/platform/directory'
    | '/admin/platform/email-domains'
    | '/admin/platform/marketplace'
    | '/admin/platform/overview'
    | '/admin/platform/reserved-slugs'
    | '/admin/platform/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/verify-otp'
    | '/account'
    | '/availability'
    | '/bookings'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/auth/email-hook'
    | '/business-id/$businessId'
    | '/business/$businessSlug'
    | '/business/signup'
    | '/salon/$salonId'
    | '/staff/signup'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/calendar'
    | '/admin/confirmations'
    | '/admin/customers'
    | '/admin/marketplace'
    | '/admin/my-appointments'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/reschedule/$bookingId'
    | '/admin'
    | '/admin/platform/auth-policies'
    | '/admin/platform/businesses'
    | '/admin/platform/categories'
    | '/admin/platform/countries'
    | '/admin/platform/directory'
    | '/admin/platform/email-domains'
    | '/admin/platform/marketplace'
    | '/admin/platform/overview'
    | '/admin/platform/reserved-slugs'
    | '/admin/platform/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/verify-otp'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/availability'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/profile'
    | '/auth/email-hook'
    | '/business-id/$businessId'
    | '/business/$businessSlug'
    | '/business/signup'
    | '/salon/$salonId'
    | '/staff/signup'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/availability'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/confirmations'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/marketplace'
    | '/_authenticated/admin/my-appointments'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/reschedule/$bookingId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/platform/auth-policies'
    | '/_authenticated/admin/platform/businesses'
    | '/_authenticated/admin/platform/categories'
    | '/_authenticated/admin/platform/countries'
    | '/_authenticated/admin/platform/directory'
    | '/_authenticated/admin/platform/email-domains'
    | '/_authenticated/admin/platform/marketplace'
    | '/_authenticated/admin/platform/overview'
    | '/_authenticated/admin/platform/reserved-slugs'
    | '/_authenticated/admin/platform/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  BusinessIdBusinessIdRoute: typeof BusinessIdBusinessIdRoute
  BusinessBusinessSlugRoute: typeof BusinessBusinessSlugRoute
  BusinessSignupRoute: typeof BusinessSignupRoute
  SalonSalonIdRoute: typeof SalonSalonIdRoute
  StaffSignupRoute: typeof StaffSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/email-hook': {
      id: '/auth/email-hook'
      path: '/email-hook'
      fullPath: '/auth/email-hook'
      preLoaderRoute: typeof AuthEmailHookRouteImport
      parentRoute: typeof AuthRoute
    }
    '/business-id/$businessId': {
      id: '/business-id/$businessId'
      path: '/business-id/$businessId'
      fullPath: '/business-id/$businessId'
      preLoaderRoute: typeof BusinessIdBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessSlug': {
      id: '/business/$businessSlug'
      path: '/business/$businessSlug'
      fullPath: '/business/$businessSlug'
      preLoaderRoute: typeof BusinessBusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/signup': {
      id: '/business/signup'
      path: '/business/signup'
      fullPath: '/business/signup'
      preLoaderRoute: typeof BusinessSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$salonId': {
      id: '/salon/$salonId'
      path: '/salon/$salonId'
      fullPath: '/salon/$salonId'
      preLoaderRoute: typeof SalonSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/signup': {
      id: '/staff/signup'
      path: '/staff/signup'
      fullPath: '/staff/signup'
      preLoaderRoute: typeof StaffSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/availability': {
      id: '/_authenticated/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AuthenticatedAdminAvailabilityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/confirmations': {
      id: '/_authenticated/admin/confirmations'
      path: '/confirmations'
      fullPath: '/admin/confirmations'
      preLoaderRoute: typeof AuthenticatedAdminConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marketplace': {
      id: '/_authenticated/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/my-appointments': {
      id: '/_authenticated/admin/my-appointments'
      path: '/my-appointments'
      fullPath: '/admin/my-appointments'
      preLoaderRoute: typeof AuthenticatedAdminMyAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/reschedule/$bookingId': {
      id: '/_authenticated/reschedule/$bookingId'
      path: '/reschedule/$bookingId'
      fullPath: '/reschedule/$bookingId'
      preLoaderRoute: typeof AuthenticatedRescheduleBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/platform/auth-policies': {
      id: '/_authenticated/admin/platform/auth-policies'
      path: '/platform/auth-policies'
      fullPath: '/admin/platform/auth-policies'
      preLoaderRoute: typeof AuthenticatedAdminPlatformAuthPoliciesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/businesses': {
      id: '/_authenticated/admin/platform/businesses'
      path: '/platform/businesses'
      fullPath: '/admin/platform/businesses'
      preLoaderRoute: typeof AuthenticatedAdminPlatformBusinessesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/categories': {
      id: '/_authenticated/admin/platform/categories'
      path: '/platform/categories'
      fullPath: '/admin/platform/categories'
      preLoaderRoute: typeof AuthenticatedAdminPlatformCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/countries': {
      id: '/_authenticated/admin/platform/countries'
      path: '/platform/countries'
      fullPath: '/admin/platform/countries'
      preLoaderRoute: typeof AuthenticatedAdminPlatformCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/directory': {
      id: '/_authenticated/admin/platform/directory'
      path: '/platform/directory'
      fullPath: '/admin/platform/directory'
      preLoaderRoute: typeof AuthenticatedAdminPlatformDirectoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/email-domains': {
      id: '/_authenticated/admin/platform/email-domains'
      path: '/platform/email-domains'
      fullPath: '/admin/platform/email-domains'
      preLoaderRoute: typeof AuthenticatedAdminPlatformEmailDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/marketplace': {
      id: '/_authenticated/admin/platform/marketplace'
      path: '/platform/marketplace'
      fullPath: '/admin/platform/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminPlatformMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/overview': {
      id: '/_authenticated/admin/platform/overview'
      path: '/platform/overview'
      fullPath: '/admin/platform/overview'
      preLoaderRoute: typeof AuthenticatedAdminPlatformOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/reserved-slugs': {
      id: '/_authenticated/admin/platform/reserved-slugs'
      path: '/platform/reserved-slugs'
      fullPath: '/admin/platform/reserved-slugs'
      preLoaderRoute: typeof AuthenticatedAdminPlatformReservedSlugsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform/users': {
      id: '/_authenticated/admin/platform/users'
      path: '/platform/users'
      fullPath: '/admin/platform/users'
      preLoaderRoute: typeof AuthenticatedAdminPlatformUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminAvailabilityRoute: typeof AuthenticatedAdminAvailabilityRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminConfirmationsRoute: typeof AuthenticatedAdminConfirmationsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminMyAppointmentsRoute: typeof AuthenticatedAdminMyAppointmentsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPlatformAuthPoliciesRoute: typeof AuthenticatedAdminPlatformAuthPoliciesRoute
  AuthenticatedAdminPlatformBusinessesRoute: typeof AuthenticatedAdminPlatformBusinessesRoute
  AuthenticatedAdminPlatformCategoriesRoute: typeof AuthenticatedAdminPlatformCategoriesRoute
  AuthenticatedAdminPlatformCountriesRoute: typeof AuthenticatedAdminPlatformCountriesRoute
  AuthenticatedAdminPlatformDirectoryRoute: typeof AuthenticatedAdminPlatformDirectoryRoute
  AuthenticatedAdminPlatformEmailDomainsRoute: typeof AuthenticatedAdminPlatformEmailDomainsRoute
  AuthenticatedAdminPlatformMarketplaceRoute: typeof AuthenticatedAdminPlatformMarketplaceRoute
  AuthenticatedAdminPlatformOverviewRoute: typeof AuthenticatedAdminPlatformOverviewRoute
  AuthenticatedAdminPlatformReservedSlugsRoute: typeof AuthenticatedAdminPlatformReservedSlugsRoute
  AuthenticatedAdminPlatformUsersRoute: typeof AuthenticatedAdminPlatformUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
    AuthenticatedAdminAvailabilityRoute: AuthenticatedAdminAvailabilityRoute,
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminConfirmationsRoute: AuthenticatedAdminConfirmationsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
    AuthenticatedAdminMyAppointmentsRoute:
      AuthenticatedAdminMyAppointmentsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPlatformAuthPoliciesRoute:
      AuthenticatedAdminPlatformAuthPoliciesRoute,
    AuthenticatedAdminPlatformBusinessesRoute:
      AuthenticatedAdminPlatformBusinessesRoute,
    AuthenticatedAdminPlatformCategoriesRoute:
      AuthenticatedAdminPlatformCategoriesRoute,
    AuthenticatedAdminPlatformCountriesRoute:
      AuthenticatedAdminPlatformCountriesRoute,
    AuthenticatedAdminPlatformDirectoryRoute:
      AuthenticatedAdminPlatformDirectoryRoute,
    AuthenticatedAdminPlatformEmailDomainsRoute:
      AuthenticatedAdminPlatformEmailDomainsRoute,
    AuthenticatedAdminPlatformMarketplaceRoute:
      AuthenticatedAdminPlatformMarketplaceRoute,
    AuthenticatedAdminPlatformOverviewRoute:
      AuthenticatedAdminPlatformOverviewRoute,
    AuthenticatedAdminPlatformReservedSlugsRoute:
      AuthenticatedAdminPlatformReservedSlugsRoute,
    AuthenticatedAdminPlatformUsersRoute: AuthenticatedAdminPlatformUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRescheduleBookingIdRoute: typeof AuthenticatedRescheduleBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRescheduleBookingIdRoute: AuthenticatedRescheduleBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthEmailHookRoute: typeof AuthEmailHookRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailHookRoute: AuthEmailHookRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  BusinessIdBusinessIdRoute: BusinessIdBusinessIdRoute,
  BusinessBusinessSlugRoute: BusinessBusinessSlugRoute,
  BusinessSignupRoute: BusinessSignupRoute,
  SalonSalonIdRoute: SalonSalonIdRoute,
  StaffSignupRoute: StaffSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
